2021-12-11 14:00:49,798 ERROR: Exception on /login [GET] [in /home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457] 
Traceback (most recent call last):
  File "/home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/zeaiter/Documents/Web Tutorials/microblog/app/routes.py", line 52, in login
    return render_template('login.html', title='Sign In', form=test)
NameError: name 'test' is not defined
2021-12-11 14:34:35,742 INFO: Microblog startup [in /home/zeaiter/Documents/Web Tutorials/microblog/app/__init__.py:46] 

2021-12-11 14:34:38,949 ERROR: Exception on /login [GET] [in /home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457] 
Traceback (most recent call last):
  File "/home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zeaiter/Documents/Web Tutorials/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/zeaiter/Documents/Web Tutorials/microblog/app/routes.py", line 52, in login
    return render_template('login.html', title='Sign In', form=test)
NameError: name 'test' is not defined
2021-12-12 15:28:29,286 INFO: Microblog startup [in /home/zeaiter/Documents/Web Tutorials/microblog/app/__init__.py:50] 

2021-12-12 15:29:27,761 INFO: Microblog startup [in /home/zeaiter/Documents/Web Tutorials/microblog/app/__init__.py:50] 

2021-12-12 15:31:33,129 INFO: Microblog startup [in /home/zeaiter/Documents/Web Tutorials/microblog/app/__init__.py:50] 

